import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useLocation} from 'react-router-dom';
import {BookOpen,LayoutDashboard,Library,ReceiptText,Users,Plus,Edit3,Trash2,Search,ArrowDownToLine,ArrowUpFromLine,Menu,X,Shield,UserRound,AlertTriangle} from 'lucide-react';
import './style.css';

const seedBooks=[
{id:'B001',title:'Things Fall Apart',author:'Chinua Achebe',genre:'Fiction',isbn:'9780385474542',quantity:6},
{id:'B002',title:'The Alchemist',author:'Paulo Coelho',genre:'Fiction',isbn:'9780061122415',quantity:4},
{id:'B003',title:'Clean Code',author:'Robert C. Martin',genre:'Technology',isbn:'9780132350884',quantity:2},
{id:'B004',title:'Atomic Habits',author:'James Clear',genre:'Self Development',isbn:'9780735211292',quantity:8},
{id:'B005',title:'Introduction to Algorithms',author:'Thomas C. Cormen',genre:'Technology',isbn:'9780262046305',quantity:1}];
const seedUsers=[{id:'ADM001',name:'Library Admin',membershipId:'ADM001',role:'Admin',password:'admin123'},{id:'MEM001',name:'Tsepo Mokoena',membershipId:'MEM001',role:'Member',password:'member123'}];
const seedTx=[{id:'TX001',bookId:'B004',bookTitle:'Atomic Habits',type:'Borrow',quantity:1,user:'Tsepo Mokoena',date:'2026-09-28T10:30:00'},{id:'TX002',bookId:'B001',bookTitle:'Things Fall Apart',type:'Add Stock',quantity:2,user:'Library Admin',date:'2026-09-27T14:15:00'}];
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
function App(){
 const [books,setBooks]=useState(()=>get('lf_books',seedBooks)),[users,setUsers]=useState(()=>get('lf_users',seedUsers)),[tx,setTx]=useState(()=>get('lf_tx',seedTx)),[me,setMe]=useState(()=>get('lf_me',null));
 const [page,setPage]=useState(window.location.hash.replace('#','')||'dashboard'); const [mobile,setMobile]=useState(false);
 useEffect(()=>localStorage.setItem('lf_books',JSON.stringify(books)),[books]);useEffect(()=>localStorage.setItem('lf_users',JSON.stringify(users)),[users]);useEffect(()=>localStorage.setItem('lf_tx',JSON.stringify(tx)),[tx]);useEffect(()=>me?localStorage.setItem('lf_me',JSON.stringify(me)):localStorage.removeItem('lf_me'),[me]);
 useEffect(()=>{const f=()=>setPage(location.hash.replace('#','')||'dashboard');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);
 const nav=p=>{location.hash=p;setPage(p);setMobile(false)};
 if(!me)return <Login onLogin={(u)=>{setMe(u);nav('dashboard')}} users={users}/>;
 const content={dashboard:<Dashboard books={books} users={users} tx={tx}/>,books:<Books books={books} setBooks={setBooks}/>,transactions:<Transactions books={books} setBooks={setBooks} tx={tx} setTx={setTx} me={me}/>,users:<UsersPage users={users} setUsers={setUsers} me={me}/>}[page]||<Dashboard books={books} users={users} tx={tx}/>;
 return <div className="shell"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><span className="brandmark"><BookOpen/></span><div><b>LibraFlow</b><small>Community Library</small></div></div><p className="navlabel">MAIN MENU</p>{[['dashboard','Dashboard',LayoutDashboard],['books','Book Management',Library],['transactions','Transactions',ReceiptText],['users','User Management',Users]].map(([p,l,I])=><button className={'nav '+(page===p?'active':'')} onClick={()=>nav(p)} key={p}><I size={18}/>{l}</button>)}<div className="sidebottom"><div className="mini"><span className="avatar">{me.name[0]}</span><div><b>{me.name}</b><small>{me.role}</small></div></div><button className="signout" onClick={()=>{setMe(null);location.hash='login'}}>Sign out</button></div></aside><section className="main"><header><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div><span className="eyebrow">LIBRARY MANAGEMENT</span><h1>{page==='dashboard'?'Dashboard':page==='books'?'Book Management':page==='transactions'?'Transactions':'User Management'}</h1></div><div className="headuser"><span className="avatar">{me.name[0]}</span><div><b>{me.name}</b><small>{me.role}</small></div></div></header><main>{content}</main></section></div>
}
function Login({users,onLogin}){const [id,setId]=useState('ADM001'),[pw,setPw]=useState('admin123'),[err,setErr]=useState('');return <div className="login"><div className="loginbox"><span className="loginicon"><BookOpen/></span><span className="eyebrow">COMMUNITY LIBRARY</span><h1>Welcome back.</h1><p>Sign in to manage books, stock and library users.</p><form onSubmit={e=>{e.preventDefault();const u=users.find(x=>x.membershipId.toLowerCase()===id.toLowerCase()&&x.password===pw);u?onLogin(u):setErr('Invalid membership ID or password.')}}><label>Membership ID<input value={id} onChange={e=>setId(e.target.value)}/></label><label>Password<input type="password" value={pw} onChange={e=>setPw(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary full">Sign in</button></form><div className="demo"><b>Demo:</b> ADM001 / admin123</div></div></div>}
function Stat({title,value,hint,I}){return <div className="stat"><span className="staticon"><I/></span><div><small>{title}</small><strong>{value}</strong><small>{hint}</small></div></div>}
function Status({q}){return <span className={'status '+(q<2?'danger':q<5?'warn':'ok')}>{q<2?'Low stock':q<5?'Available':'In stock'}</span>}
function Dashboard({books,users,tx}){const copies=books.reduce((a,b)=>a+b.quantity,0),low=books.filter(b=>b.quantity<2);return <><div className="intro"><div><h2>Good to see you.</h2><p>Here is today's library overview.</p></div></div><div className="stats"><Stat title="Book titles" value={books.length} hint="Registered titles" I={BookOpen}/><Stat title="Copies in stock" value={copies} hint="Across all titles" I={Library}/><Stat title="Low stock" value={low.length} hint="Needs attention" I={AlertTriangle}/><Stat title="Users" value={users.length} hint="Registered accounts" I={Users}/></div><div className="cols"><section className="panel"><div className="panelhead"><b>Book availability</b><small>Current quantity by title</small></div><Table><thead><tr><th>Book</th><th>Genre</th><th>Qty</th><th>Status</th></tr></thead><tbody>{books.map(b=><tr key={b.id}><td><b>{b.title}</b><small>{b.author}</small></td><td>{b.genre}</td><td>{b.quantity}</td><td><Status q={b.quantity}/></td></tr>)}</tbody></Table></section><section className="panel"><div className="panelhead"><b>Recent transactions</b><small>Latest stock activity</small></div><div className="activity">{tx.slice(0,6).map(t=><div className="activityrow" key={t.id}><span className={'dot '+(t.type==='Borrow'?'borrow':'add')}></span><div><b>{t.type==='Borrow'?'Borrowed':'Stock added'}</b><small>{t.bookTitle}</small></div><time>{new Date(t.date).toLocaleDateString()}</time></div>)}</div></section></div></>}
function Table({children}){return <div className="tablewrap"><table>{children}</table></div>}
function Books({books,setBooks}){const [q,setQ]=useState(''),[edit,setEdit]=useState(null),[form,setForm]=useState({title:'',author:'',genre:'',isbn:'',quantity:1}),[err,setErr]=useState('');const filtered=books.filter(b=>[b.title,b.author,b.genre,b.isbn].join(' ').toLowerCase().includes(q.toLowerCase()));const open=b=>{setEdit(b||null);setForm(b?{...b}:{title:'',author:'',genre:'',isbn:'',quantity:1});setErr('')};const save=e=>{e.preventDefault();if(!form.title||!form.author||!form.genre||!form.isbn){setErr('Complete all fields.');return}if(form.quantity<0){setErr('Quantity cannot be negative.');return}if(edit)setBooks(bs=>bs.map(b=>b.id===edit.id?{...b,...form,quantity:+form.quantity}:b));else setBooks(bs=>[...bs,{...form,id:'B'+Date.now(),quantity:+form.quantity}]);setEdit('closed')};return <><div className="intro"><div><h2>Manage your collection.</h2><p>Add, edit and remove library books.</p></div><button className="primary" onClick={()=>open() }><Plus size={17}/> Add new book</button></div><section className="panel"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search title, author, genre or ISBN..." value={q} onChange={e=>setQ(e.target.value)}/></div><small>{filtered.length} titles</small></div><Table><thead><tr><th>Title</th><th>Genre</th><th>ISBN</th><th>Quantity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td><b>{b.title}</b><small>{b.author}</small></td><td>{b.genre}</td><td>{b.isbn}</td><td>{b.quantity}</td><td><Status q={b.quantity}/></td><td><button className="icon" onClick={()=>open(b)}><Edit3 size={16}/></button><button className="icon dangericon" onClick={()=>confirm('Delete this book?')&&setBooks(bs=>bs.filter(x=>x.id!==b.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></Table></section>{edit&&edit!=='closed'&&<Modal title={edit?'Update book':'Add new book'} close={()=>setEdit(null)}><form className="gridform" onSubmit={save}><Field label="Title"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Author"><input value={form.author} onChange={e=>setForm({...form,author:e.target.value})}/></Field><Field label="Genre"><select value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}><option value="">Select genre</option>{['Fiction','Technology','Self Development','Education','Biography','History'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="ISBN"><input value={form.isbn} onChange={e=>setForm({...form,isbn:e.target.value})}/></Field><Field label="Initial Quantity"><input type="number" min="0" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field>{err&&<div className="error wide">{err}</div>}<div className="actions wide"><button type="button" className="secondary" onClick={()=>setEdit(null)}>Cancel</button><button className="primary">{edit?'Save changes':'Add book'}</button></div></form></Modal>}</>}
function Transactions({books,setBooks,tx,setTx,me}){const [open,setOpen]=useState(false),[form,setForm]=useState({bookId:books[0]?.id||'',type:'Borrow',quantity:1}),[err,setErr]=useState('');const save=e=>{e.preventDefault();const b=books.find(x=>x.id===form.bookId),n=+form.quantity;if(!b||n<1)return setErr('Enter a valid quantity.');if(form.type==='Borrow'&&b.quantity<n)return setErr(`Only ${b.quantity} copies are available.`);setBooks(bs=>bs.map(x=>x.id===b.id?{...x,quantity:form.type==='Borrow'?x.quantity-n:x.quantity+n}:x));setTx(ts=>[{id:'TX'+Date.now(),bookId:b.id,bookTitle:b.title,type:form.type,quantity:n,user:me.name,date:new Date().toISOString()},...ts]);setOpen(false);setErr('')};return <><div className="intro"><div><h2>Stock transactions.</h2><p>Record books borrowed and new stock received.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/> New transaction</button></div><div className="quick"><div><ArrowDownToLine/><b>Borrow books</b><small>Deduct copies from stock</small></div><div><ArrowUpFromLine/><b>Add stock</b><small>Record new arrivals</small></div></div><section className="panel"><div className="panelhead"><b>Transaction history</b><small>All recorded stock movements</small></div><Table><thead><tr><th>Book</th><th>Type</th><th>Quantity</th><th>User</th><th>Date</th></tr></thead><tbody>{tx.map(t=><tr key={t.id}><td><b>{t.bookTitle}</b><small>{t.id}</small></td><td><span className={'status '+(t.type==='Borrow'?'warn':'ok')}>{t.type}</span></td><td>{t.quantity}</td><td>{t.user}</td><td>{new Date(t.date).toLocaleString()}</td></tr>)}</tbody></Table></section>{open&&<Modal title="New stock transaction" close={()=>setOpen(false)}><form onSubmit={save}><Field label="Transaction type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Borrow</option><option>Add Stock</option></select></Field><Field label="Book"><select value={form.bookId} onChange={e=>setForm({...form,bookId:e.target.value})}>{books.map(b=><option key={b.id} value={b.id}>{b.title} — {b.quantity} available</option>)}</select></Field><Field label="Quantity"><input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field>{err&&<div className="error">{err}</div>}<div className="actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Save transaction</button></div></form></Modal>}</>}
function UsersPage({users,setUsers,me}){const [open,setOpen]=useState(false),[edit,setEdit]=useState(null),[form,setForm]=useState({name:'',membershipId:'',role:'Member',password:''}),[err,setErr]=useState('');const show=u=>{setEdit(u||null);setForm(u?{...u,password:''}:{name:'',membershipId:'',role:'Member',password:''});setErr('');setOpen(true)};const save=e=>{e.preventDefault();if(!form.name||!form.membershipId||(!edit&&!form.password))return setErr('Complete the required fields.');if(edit){setUsers(us=>us.map(u=>u.id===edit.id?{...u,...form,password:form.password||u.password}:u))}else{if(users.some(u=>u.membershipId.toLowerCase()===form.membershipId.toLowerCase()))return setErr('Membership ID already exists.');setUsers(us=>[...us,{...form,id:form.membershipId.toUpperCase()}])}setOpen(false)};return <><div className="intro"><div><h2>People & permissions.</h2><p>Manage membership accounts and roles.</p></div><button className="primary" onClick={()=>show()}><Plus size={17}/> Add user</button></div><section className="panel"><Table><thead><tr><th>User</th><th>Membership ID</th><th>Role</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div className="usercell"><span className="avatar">{u.name[0]}</span><div><b>{u.name}</b><small>{u.role==='Admin'?'Administrator account':'Library member'}</small></div></div></td><td>{u.membershipId}</td><td><span className="role">{u.role==='Admin'?<Shield size={13}/>:<UserRound size={13}/>} {u.role}</span></td><td><button className="icon" onClick={()=>show(u)}><Edit3 size={16}/></button><button className="icon dangericon" disabled={u.id===me.id} onClick={()=>confirm('Delete this user?')&&setUsers(us=>us.filter(x=>x.id!==u.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></Table></section>{open&&<Modal title={edit?'Update user':'Add new user'} close={()=>setOpen(false)}><form onSubmit={save}><Field label="Name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Membership ID"><input value={form.membershipId} onChange={e=>setForm({...form,membershipId:e.target.value})}/></Field><Field label="Role"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Member</option><option>Admin</option></select></Field><Field label="Password"><input type="password" value={form.password} placeholder={edit?'Leave blank to keep current':''} onChange={e=>setForm({...form,password:e.target.value})}/></Field>{err&&<div className="error">{err}</div>}<div className="actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Save user</button></div></form></Modal>}</>}
function Field({label,children}){return <label>{label}{children}</label>};function Modal({title,close,children}){return <div className="backdrop"><div className="modal"><div className="modalhead"><h2>{title}</h2><button className="icon" onClick={close}><X/></button></div>{children}</div></div>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
